// packages/react/src/components/sidebar/TrackedChangeCard.tsx
import type { Comment } from '@eigenpal/docx-editor-core/types/content';
import { MaterialSymbol } from '../ui/Icons';
import type { SidebarItemRenderProps } from '../../plugin-api/types';
import type { TrackedChangeEntry } from './cardUtils';
import { formatDate, getInitials, avatarStyle, ICON_BUTTON_STYLE, truncateText } from './cardUtils';
import { ReplyThread } from './ReplyThread';
import { ReplyInput } from './ReplyInput';
import { CARD_STYLE_COLLAPSED, CARD_STYLE_EXPANDED } from './cardStyles';
import { useTranslation } from '../../i18n';

export interface TrackedChangeCardProps extends SidebarItemRenderProps {
  change: TrackedChangeEntry;
  replies: Comment[];
  onAccept?: (from: number, to: number) => void;
  onReject?: (from: number, to: number) => void;
  /** For paragraph-mark entries — accept/reject by `w:id`. */
  onAcceptById?: (revisionId: number) => void;
  onRejectById?: (revisionId: number) => void;
  onReply?: (revisionId: number, text: string) => void;
}

export function TrackedChangeCard({
  change,
  replies,
  isExpanded,
  onToggleExpand,
  measureRef,
  onAccept,
  onReject,
  onAcceptById,
  onRejectById,
  onReply,
}: TrackedChangeCardProps) {
  const { t } = useTranslation();
  const authorName = change.author || t('trackedChanges.unknown');

  // Dispatch by `revisionId` whenever the host wired the by-id handlers.
  // A single coalesced edit can scatter sites across paragraphs (inline
  // marks + pPrIns attrs sharing one id); a range-based accept only clears
  // marks within the entry's (from, to), leaving sibling pPrIns attrs
  // behind so the user would need a second Accept. By-id walks every site
  // sharing the id in one pass — correct for all entry types.
  const handleAccept = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (onAcceptById) {
      onAcceptById(change.revisionId);
      // A 'replacement' entry collapses an adjacent deletion + insertion
      // into one card. The two halves carry distinct `w:id` values
      // (sharing would trip the OOXML move-pair serializer), so we need
      // to dispatch both to clear every site in one click.
      if (change.type === 'replacement' && change.insertionRevisionId != null) {
        onAcceptById(change.insertionRevisionId);
      }
    } else {
      onAccept?.(change.from, change.to);
    }
  };
  const handleReject = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (onRejectById) {
      onRejectById(change.revisionId);
      if (change.type === 'replacement' && change.insertionRevisionId != null) {
        onRejectById(change.insertionRevisionId);
      }
    } else {
      onReject?.(change.from, change.to);
    }
  };

  return (
    <div
      ref={measureRef}
      className="docx-tracked-change-card"
      onClick={() => onToggleExpand()}
      onMouseDown={(e) => e.stopPropagation()}
      style={isExpanded ? CARD_STYLE_EXPANDED : CARD_STYLE_COLLAPSED}
    >
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10 }}>
        <div style={avatarStyle(authorName)}>{getInitials(authorName)}</div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: '#202124' }}>{authorName}</div>
          {change.date && (
            <div style={{ fontSize: 11, color: '#5f6368' }}>{formatDate(change.date)}</div>
          )}
        </div>
        {isExpanded && (
          <div style={{ display: 'flex', gap: 4, marginTop: 2 }}>
            <button onClick={handleAccept} title={t('common.accept')} style={ICON_BUTTON_STYLE}>
              <MaterialSymbol name="check" size={20} />
            </button>
            <button onClick={handleReject} title={t('common.reject')} style={ICON_BUTTON_STYLE}>
              <MaterialSymbol name="close" size={20} />
            </button>
          </div>
        )}
      </div>

      <div style={{ fontSize: 13, lineHeight: '20px', color: '#202124', marginTop: 6 }}>
        {change.type === 'replacement' ? (
          <>
            {t('trackedChanges.replaced')}{' '}
            <span style={{ color: '#c5221f', fontWeight: 500 }}>
              &quot;{truncateText(change.deletedText || '')}&quot;
            </span>{' '}
            {t('trackedChanges.with')}{' '}
            <span style={{ color: '#137333', fontWeight: 500 }}>
              &quot;{truncateText(change.text)}&quot;
            </span>
          </>
        ) : change.type === 'paragraphMarkInsertion' ? (
          <>
            {t('revisions.paragraphMarkInserted')}
            {change.text ? (
              <>
                {': '}
                <span style={{ color: '#137333', fontWeight: 500 }}>
                  &quot;{truncateText(change.text)}&quot;
                </span>
              </>
            ) : null}
          </>
        ) : change.type === 'paragraphMarkDeletion' ? (
          <>
            {t('revisions.paragraphMarkDeleted')}
            {change.text ? (
              <>
                {': '}
                <span style={{ color: '#c5221f', fontWeight: 500 }}>
                  &quot;{truncateText(change.text)}&quot;
                </span>
              </>
            ) : null}
          </>
        ) : change.type === 'paragraphPropertiesChanged' ? (
          <>
            {t('revisions.paragraphPropertiesChanged')}
            {change.text ? (
              <>
                {': '}
                <span style={{ color: '#5f6368', fontWeight: 500 }}>
                  &quot;{truncateText(change.text)}&quot;
                </span>
              </>
            ) : null}
          </>
        ) : change.type === 'rowInserted' ? (
          <span style={{ color: '#137333', fontWeight: 500 }}>{t('revisions.rowInserted')}</span>
        ) : change.type === 'rowDeleted' ? (
          <span style={{ color: '#c5221f', fontWeight: 500 }}>{t('revisions.rowDeleted')}</span>
        ) : change.type === 'cellInserted' ? (
          <span style={{ color: '#137333', fontWeight: 500 }}>{t('revisions.cellInserted')}</span>
        ) : change.type === 'cellDeleted' ? (
          <span style={{ color: '#c5221f', fontWeight: 500 }}>{t('revisions.cellDeleted')}</span>
        ) : change.type === 'cellMerged' ? (
          <span style={{ color: '#5f6368', fontWeight: 500 }}>{t('revisions.cellMerged')}</span>
        ) : change.type === 'rowPropertiesChanged' ? (
          <span style={{ color: '#5f6368' }}>{t('revisions.rowPropertiesChanged')}</span>
        ) : change.type === 'cellPropertiesChanged' ? (
          <span style={{ color: '#5f6368' }}>{t('revisions.cellPropertiesChanged')}</span>
        ) : change.type === 'tablePropertiesChanged' ? (
          <span style={{ color: '#5f6368' }}>{t('revisions.tablePropertiesChanged')}</span>
        ) : (
          <>
            {change.type === 'insertion' ? t('trackedChanges.added') : t('trackedChanges.deleted')}{' '}
            <span
              style={{
                color: change.type === 'insertion' ? '#137333' : '#c5221f',
                fontWeight: 500,
              }}
            >
              &quot;{truncateText(change.text)}&quot;
            </span>
          </>
        )}
      </div>

      <ReplyThread replies={replies} isExpanded={isExpanded} />

      {isExpanded && <ReplyInput onSubmit={(text) => onReply?.(change.revisionId, text)} />}
    </div>
  );
}

// packages/vue/src/components/sidebar/TrackedChangeCard.vue
<!--
  Mirror of packages/react/src/components/sidebar/TrackedChangeCard.tsx.
  Same chrome (collapsed/expanded), same author/date layout,
  insertion/deletion/replacement formatting, accept/reject icon
  buttons in expanded state.
-->
<template>
  <div
    class="tc-card"
    :class="{ 'tc-card--expanded': expanded }"
    @click="$emit('click')"
    @mousedown.stop
  >
    <div class="tc-card__head">
      <Avatar :name="authorName" :size="32" />
      <div class="tc-card__author-block">
        <div class="tc-card__author">{{ authorName }}</div>
        <div v-if="change.date" class="tc-card__date">{{ formatDate(change.date) }}</div>
      </div>
      <div v-if="expanded" class="tc-card__actions">
        <button class="tc-card__icon-btn" :title="t('common.accept')" @click.stop="onAccept">
          <MaterialSymbol name="check" :size="20" />
        </button>
        <button class="tc-card__icon-btn" :title="t('common.reject')" @click.stop="onReject">
          <MaterialSymbol name="close" :size="20" />
        </button>
      </div>
    </div>

    <div class="tc-card__body">
      <template v-if="change.type === 'replacement'">
        {{ t('trackedChanges.replaced') }}
        <span class="tc-card__deleted">&quot;{{ truncateText(change.deletedText || '') }}&quot;</span>
        {{ t('trackedChanges.with') }}
        <span class="tc-card__inserted">&quot;{{ truncateText(change.text) }}&quot;</span>
      </template>
      <template v-else-if="change.type === 'paragraphMarkInsertion'">
        {{ t('revisions.paragraphMarkInserted') }}<template v-if="change.text">: <span class="tc-card__inserted">&quot;{{ truncateText(change.text) }}&quot;</span></template>
      </template>
      <template v-else-if="change.type === 'paragraphMarkDeletion'">
        {{ t('revisions.paragraphMarkDeleted') }}<template v-if="change.text">: <span class="tc-card__deleted">&quot;{{ truncateText(change.text) }}&quot;</span></template>
      </template>
      <template v-else-if="change.type === 'paragraphPropertiesChanged'">
        {{ t('revisions.paragraphPropertiesChanged') }}<template v-if="change.text">: <span class="tc-card__changed">&quot;{{ truncateText(change.text) }}&quot;</span></template>
      </template>
      <template v-else-if="change.type === 'rowInserted'">
        <span class="tc-card__inserted">{{ t('revisions.rowInserted') }}</span>
      </template>
      <template v-else-if="change.type === 'rowDeleted'">
        <span class="tc-card__deleted">{{ t('revisions.rowDeleted') }}</span>
      </template>
      <template v-else-if="change.type === 'cellInserted'">
        <span class="tc-card__inserted">{{ t('revisions.cellInserted') }}</span>
      </template>
      <template v-else-if="change.type === 'cellDeleted'">
        <span class="tc-card__deleted">{{ t('revisions.cellDeleted') }}</span>
      </template>
      <template v-else-if="change.type === 'cellMerged'">
        <span class="tc-card__changed">{{ t('revisions.cellMerged') }}</span>
      </template>
      <template v-else-if="change.type === 'rowPropertiesChanged'">
        <span class="tc-card__changed">{{ t('revisions.rowPropertiesChanged') }}</span>
      </template>
      <template v-else-if="change.type === 'cellPropertiesChanged'">
        <span class="tc-card__changed">{{ t('revisions.cellPropertiesChanged') }}</span>
      </template>
      <template v-else-if="change.type === 'tablePropertiesChanged'">
        <span class="tc-card__changed">{{ t('revisions.tablePropertiesChanged') }}</span>
      </template>
      <template v-else>
        {{ change.type === 'insertion' ? t('trackedChanges.added') : t('trackedChanges.deleted') }}
        <span :class="change.type === 'insertion' ? 'tc-card__inserted' : 'tc-card__deleted'">
          &quot;{{ truncateText(change.text) }}&quot;
        </span>
      </template>
    </div>

    <!-- Reply input — mirrors React TrackedChangeCard.tsx:103. Lets
         a user thread a comment under a tracked change. -->
    <ReplyInput
      v-if="expanded"
      @submit="(text: string) => $emit('reply', change.revisionId, text)"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { TrackedChangeEntry } from './sidebarUtils';
import { formatDate, truncateText } from './sidebarUtils';
import Avatar from './Avatar.vue';
import MaterialSymbol from '../ui/MaterialSymbol.vue';
import ReplyInput from './ReplyInput.vue';
import { useTranslation } from '../../i18n';

const { t } = useTranslation();

const props = defineProps<{
  change: TrackedChangeEntry;
  expanded: boolean;
}>();

const emit = defineEmits<{
  (e: 'click'): void;
  (e: 'accept-by-id', revisionId: number): void;
  (e: 'reject-by-id', revisionId: number): void;
  (e: 'reply', revisionId: number, text: string): void;
}>();

const authorName = computed(() => props.change.author || t('trackedChanges.unknown'));

// Dispatch by `revisionId` whenever the host wired the by-id channel.
// A single coalesced edit can scatter sites across paragraphs (inline
// marks + pPrIns attrs sharing one id); a range-based accept only clears
// marks within the entry's (from, to), leaving sibling pPrIns attrs
// behind so the user would need a second Accept. By-id walks every site
// sharing the id in one pass — correct for all entry types.
function onAccept() {
  emit('accept-by-id', props.change.revisionId);
  // 'replacement' carries distinct ids for the deletion vs the insertion
  // (sharing would trip the OOXML move-pair serializer); dispatch both
  // so one click clears every site of the conceptual change.
  if (props.change.type === 'replacement' && props.change.insertionRevisionId != null) {
    emit('accept-by-id', props.change.insertionRevisionId);
  }
}

function onReject() {
  emit('reject-by-id', props.change.revisionId);
  if (props.change.type === 'replacement' && props.change.insertionRevisionId != null) {
    emit('reject-by-id', props.change.insertionRevisionId);
  }
}
</script>

<style scoped>
.tc-card {
  padding: 8px 10px;
  border-radius: 8px;
  background: #f8fbff;
  cursor: pointer;
  box-shadow:
    0 1px 3px rgba(60, 64, 67, 0.2),
    0 2px 6px rgba(60, 64, 67, 0.08);
  margin-bottom: 6px;
  transition: box-shadow 0.15s ease, background-color 0.15s ease, padding 0.15s ease;
}
.tc-card--expanded {
  padding: 10px 12px;
  background: #fff;
  box-shadow:
    0 1px 3px rgba(60, 64, 67, 0.3),
    0 4px 8px 3px rgba(60, 64, 67, 0.15);
}
.tc-card__head {
  display: flex;
  align-items: flex-start;
  gap: 10px;
}
.tc-card__author-block {
  flex: 1;
  min-width: 0;
}
.tc-card__author {
  font-size: 13px;
  font-weight: 600;
  color: #202124;
}
.tc-card__date {
  font-size: 11px;
  color: #5f6368;
}
.tc-card__actions {
  display: flex;
  gap: 4px;
  margin-top: 2px;
}
.tc-card__icon-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 4px;
  color: #5f6368;
  display: flex;
  border-radius: 50%;
}
.tc-card__icon-btn:hover {
  background: rgba(60, 64, 67, 0.08);
}
.tc-card__body {
  font-size: 13px;
  line-height: 20px;
  color: #202124;
  margin-top: 6px;
}
.tc-card__deleted {
  color: #c5221f;
  font-weight: 500;
}
.tc-card__inserted {
  color: #137333;
  font-weight: 500;
}
.tc-card__changed {
  color: #5f6368;
  font-weight: 500;
}
</style>
